version: "3.8"

networks:
  url_shortener:
    driver: bridge

services:
  service_url_shortener:
    image: url_shortener:latest
    container_name: 'url-shortener'
    depends_on:
      - "url_shortener_db"
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      MongoDbSettings:ConnectionString: "mongodb://${DB_USER}:${DB_PASSWORD}@url_shortener_db/${DB_NAME}?authSource=admin"
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - url_shortener

  url_shortener_db:
    image: mongo
    container_name: 'url-shortener-db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - '/data/configdb:/data/configdb'
      - '/data/db:/data/db'
    networks:
      - url_shortener

  url_shortener_mongo-express:
    image: mongo-express
    container_name: 'url-shortener-mongo-express'
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: 'url-shortener-db'
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
    depends_on:
      - "url_shortener_db"
    networks:
      - url_shortener